"""add crawl_priority to books

Revision ID: 038a492da2ec
Revises: 6d0ce980624a
Create Date: 2026-06-28 11:35:46.478075

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '038a492da2ec'
down_revision: str | Sequence[str] | None = '6d0ce980624a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('crawl_priority', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_books_crawl_priority'), 'books', ['crawl_priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_crawl_priority'), table_name='books')
    op.drop_column('books', 'crawl_priority')
    # ### end Alembic commands ###
