"""add index on pages.source_url

Revision ID: 20ebd2b65836
Revises: 038a492da2ec
Create Date: 2026-06-28 15:38:11.118063

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '20ebd2b65836'
down_revision: str | Sequence[str] | None = '038a492da2ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pages_source_url'), 'pages', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_source_url'), table_name='pages')
    # ### end Alembic commands ###
