"""initial schema

Revision ID: 6d0ce980624a
Revises: 
Create Date: 2026-06-27 12:45:02.549701

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6d0ce980624a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_original', sa.String(length=512), nullable=False),
    sa.Column('name_normalised', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_name_normalised'), 'authors', ['name_normalised'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('name_original', sa.String(length=512), nullable=False),
    sa.Column('name_en', sa.String(length=512), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_source_id'), 'categories', ['source_id'], unique=False)
    op.create_table('crawl_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_logs_url'), 'crawl_logs', ['url'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_book_id', sa.String(length=64), nullable=False),
    sa.Column('title_original', sa.String(length=1024), nullable=False),
    sa.Column('title_normalised', sa.String(length=1024), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('volume_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_book_id', name='uq_books_source_book_id')
    )
    op.create_index(op.f('ix_books_source_book_id'), 'books', ['source_book_id'], unique=False)
    op.create_index(op.f('ix_books_title_normalised'), 'books', ['title_normalised'], unique=False)
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'volume_number', name='uq_volumes_book_number')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=True),
    sa.Column('volume_number', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_raw', sa.Text(), nullable=True),
    sa.Column('text_normalised', sa.Text(), nullable=True),
    sa.Column('html_raw', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'volume_number', 'page_number', name='uq_pages_book_volume_page')
    )
    op.create_index(op.f('ix_pages_checksum'), 'pages', ['checksum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_checksum'), table_name='pages')
    op.drop_table('pages')
    op.drop_table('volumes')
    op.drop_table('book_authors')
    op.drop_index(op.f('ix_books_title_normalised'), table_name='books')
    op.drop_index(op.f('ix_books_source_book_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_crawl_logs_url'), table_name='crawl_logs')
    op.drop_table('crawl_logs')
    op.drop_index(op.f('ix_categories_source_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_authors_name_normalised'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
